# Generated by Django 3.0.3 on 2020-03-30 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendersolicitacao',
            name='Motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_solicitacoes.Usuario'),
        ),
        migrations.DeleteModel(
            name='Motorista',
        ),
    ]
